### ISSUE TITLE
./configure wandio http support error

### ISSUE THREAD

**Issue by reuteran** [CAIDA/bgpstream#1]
Hey,
when running ./configure I get this error:
```
configure: ---- BGPStream configuration ----
checking whether to build with data interface: broker... yes
checking whether to build with data interface: singlefile... yes
checking whether to build with data interface: csvfile... yes
checking whether to build with data interface: sqlite... no
configure: checking data interface dependencies...
checking for wandio HTTP support... configure: error: wandio HTTP support required. Ensure you have a working Internet connection and that libcurl is installed before building wandio.
```
however, when I installed wandio, its ./configure message tells me that it was compiled with libcurl:
```
configure: WANDIO version 1.0.3
configure: Compiled with compressed file (zlib) support: Yes
configure: Compiled with compressed file (bz2) support: Yes
configure: Compiled with compressed file (lzo write only) support: Yes
configure: Compiled with compressed file (lzma) support: Yes
configure: Compiled with http read (libcurl) support: Yes
```

**Comment by alistairking** [comment]
Would you mind sharing the `config.log` file from bgpstream?

**Comment by alistairking** [comment]
At the same time, can you try running:
`wandiocat http://www.apple.com/library/test/success.html`
to ensure that wandio is correctly installed and accessible.

(the apple.com domain isn't important, it was just the first http server i could think of that reliably returns simple content)

**Comment by reuteran** [comment]
wandio seems to be working:
```
$ wandiocat http://www.apple.com/library/test/success.html
<HTML><HEAD><TITLE>Success</TITLE></HEAD><BODY>Success</BODY></HTML>
```
Here is the config.log contents: 
http://pastebin.com/fb8VBky7

**Comment by alistairking** [comment]
This is an "interesting" failure.
The error message from configure:
~~~
./conftest: error while loading shared libraries: libwandio.so.1: cannot open shared object file: No such file or directory`
~~~
which normally indicates that the wandio shared library either is not installed in a system location, or the cache has not been updated. Both of which normally also cause the `wandiocat` tool to fail with the same error message.

Could you please try running `sudo ldconfig` and trying configure again, just so that we can be sure the library caches are updated.

**Comment by reuteran** [comment]
```sudo ldconfig ``` did not help, however I copied libwandio.so.1 from /usr/local/lib to /usr/lib and now everything works!

**Comment by alistairking** [comment]
I'm glad that you got things to work.
Could you tell me what OS you're using so I can try and reproduce the issue in case others run into the same problem.

**Comment by reuteran** [comment]
I am using Antergos Linux, which is Arch based.
```
Linux 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux
```

**Comment by alistairking** [comment]
Thanks, I'll give it a try.

**Comment by alistairking** [comment]
Ok, I finally found the time to try installing BGPStream on Arch linux, and ran into the same problem.

The issue is that Arch doesn't include `/usr/local/lib` in the default library search path (even though `/usr/local/bin` is in the default PATH...).
There are two solutions here:
 1. Add `/usr/local/lib` to `/etc/ld.so.conf` and then run `sudo ldconfig`
 2. Install wandio and bgpstream to `/usr` by using the `--prefix` argument to configure:
     `./configure --prefix=/usr` (this is effectively how @reuteran solved the problem)

I'll add Arch-specific install documentation to help future users.
Thanks for your help tracking this down.

**Comment by jvr1967** [comment]
> Ok, I finally found the time to try installing BGPStream on Arch linux, and ran into the same problem.
> 
> The issue is that Arch doesn't include `/usr/local/lib` in the default library search path (even though `/usr/local/bin` is in the default PATH...).
> There are two solutions here:
> 
>     1. Add `/usr/local/lib` to `/etc/ld.so.conf` and then run `sudo ldconfig`
> 
>     2. Install wandio and bgpstream to `/usr` by using the `--prefix` argument to configure:
>        `./configure --prefix=/usr` (this is effectively how @reuteran solved the problem)
> 
> 
> I'll add Arch-specific install documentation to help future users.
> Thanks for your help tracking this down.

This solution worked for me. I had tried just about everything and wandiocat was working fine even though the ./configure of BGPStream was saying it wasn't. There are obviously too many moving parts to BGPStream hence why the installation is so complicated. It's easier to compile and install the Linux kernel than it is to install BGPStream!!!
