### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by salsh** [CAIDA/bgpstream#24]
During the work on Live PRKI Origin Validation, I would like to adjust the code to the coding style. Therefore I wanted to ask if there are any contribution guidelines?

**Comment by salsh** [comment]
Ping @alistairking . After manual testing, we currently write some testing routines for the Live PRKI Origin Validation. Before we submit a PR in the next few days, we want to adjust the code so it corresponds to your contribution guidelines.

**Comment by alistairking** [comment]
I haven't replied yet because I was hoping to create a PR of my own which standardizes the code style that is used in BGPStream. Alas, I haven't had the time.

We are planning to adopt a code style that is very similar to the LLVM style: http://llvm.org/docs/CodingStandards.html and we will use the Clang-Format tool (http://clang.llvm.org/docs/ClangFormat.html) to automatically reformat the code. Attached is the style file that we'll use for clang-format.

Hope this helps.

[clang-format.txt](https://github.com/CAIDA/bgpstream/files/312271/clang-format.txt)

**Comment by salsh** [comment]
@alistairking, yes this helps. Thank you very much for the effort.
