### ISSUE TITLE
4 errors happen in make check operation

### ISSUE THREAD

**Issue by flyingsky2017** [CAIDA/bgpstream#44]
there are 4 errors in Debian GNU/Linux 8.7 (jessie) while I'm running make check, and the test-suite.log is here 
[test-suite.txt](https://github.com/CAIDA/bgpstream/files/893447/test-suite.txt)

**Comment by flyingsky2017** [comment]
could anyone help out.

**Comment by alistairking** [comment]
It seems that this is the same problem as described in Issue #34.
If you are not going to use IPv6 filters then you can probably ignore the error -- it only happens when parsing a v6 address from a string.
Of course, if you're interested in trying to patch the problem using the info in #34, we'd love a Pull Request :)

**Comment by flyingsky2017** [comment]
thank you. I will have a try.
