### ISSUE TITLE
Update Wandio link in BGPStream core installation documentation

### ISSUE THREAD

**Issue by vgiotsas** [CAIDA/bgpstream#55]
Currently, the documentation on how to install the BGPStream core provides a link to wandio 1.0.3 that appears to be dead. The following link to wandio 1.0.4 seems to be the new working link:

https://research.wand.net.nz/software/wandio/wandio-1.0.4.tar.gz

**Comment by digizeph** [comment]
I think the problem is not the resource availability, but the fact that  `curl` fails when `http` resource is redirected to `https`. I tested downloading 1.0.3 on MacOS and Ubuntu, and here are the results:

1. FAIL: `curl -O http://research.wand.net.nz/software/wandio/wandio-1.0.3.tar.gz`
1. SUCESS: `curl -O https://research.wand.net.nz/software/wandio/wandio-1.0.3.tar.gz`
1. SUCESS: `wget http://research.wand.net.nz/software/wandio/wandio-1.0.3.tar.gz`

Downloading 1.0.4 ends with the same results.

Two solutions:
1. change resource URI from `http` to `https`;
1. change downloading tool from `curl` to `wget`.

However, `wget` may not exists on certain platforms by default.

**Comment by vgiotsas** [comment]
@digizeph  you are correct.

The curl `-L` flat also works (it tells curl to follow redirects)

**Comment by alistairking** [comment]
Thanks guys. I'll update the link to use `https`.

**Comment by alistairking** [comment]
Fixed.
