### ISSUE TITLE
have you implemented the routing-table plugin for BGPCorsaro which is mentioned in your paper

### ISSUE THREAD

**Issue by compassur** [CAIDA/bgpstream#8]
i don't find this in this repository

**Comment by alistairking** [comment]
@compassur, so sorry for the extremely long delay in getting back to you about this.

We do have an implementation of the routing-table plugin, however we are not able to release it as open source at the moment (since it depends on some internal libraries). We are planning on doing the work needed for release at some point, but don't have a firm release date yet.
